[package]
name = "moose"
version = "0.1.0"
authors =["Devon Tingley <dtingley@twilit.io>"]
description = "Oxidized interpretor for the monkey programming language"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }

[dev-dependencies]
rstest = "0.16.0"
